<a href="https://colab.research.google.com/github/paras-negi2005/Applied-Machine-Learning-Lab/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

_____
**Write a program to create an array [10, 5, 7, 20, 15, -9, 33], print it, Find the maximum and minimum Value of the array**

In [1]:
import numpy as np

# Create array
arr = np.array([10, 5, 7, 20, 15, -9, 33])

# Print array
print("Array:", arr)

# Find maximum and minimum
print("Maximum value:", arr.max())
print("Minimum value:", arr.min())


Array: [10  5  7 20 15 -9 33]
Maximum value: 33
Minimum value: -9


______
**Write a program to accept an array of elements and find the maximum without using max function**

In [2]:
# Accept array elements from user
arr = list(map(int, input("Enter elements separated by space: ").split()))

# Assume first element is maximum
maximum = arr[0]

# Find maximum manually
for num in arr:
    if num > maximum:
        maximum = num

print("Maximum value:", maximum)


Enter elements separated by space: 12 23 23 12 4 345 34 342 
Maximum value: 345


___
**Write a program to accept two matrices [[1,2],[3,4]],   [[2,4],[6,8]]and find the sum and subtraction of two matrices**

In [3]:
# Define matrices
A = np.array([[1, 2],[3, 4]])

B = np.array([[2, 4],[6, 8]])

# Sum of matrices
sum_matrix = A + B

# Subtraction of matrices
sub_matrix = A - B

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nSum of matrices:\n", sum_matrix)
print("\nSubtraction of matrices:\n", sub_matrix)


Matrix A:
 [[1 2]
 [3 4]]

Matrix B:
 [[2 4]
 [6 8]]

Sum of matrices:
 [[ 3  6]
 [ 9 12]]

Subtraction of matrices:
 [[-1 -2]
 [-3 -4]]


___
**Write a program to generate a ranodom matrix of size 5 X 6. Add another row containing random elements to it. Find the sum of each row.**

In [4]:
# Generate random 5x6 matrix
matrix = np.random.randint(1, 50, size=(5, 6))

print("Original 5x6 Matrix:\n", matrix)

# Generate another random row
new_row = np.random.randint(1, 50, size=(1, 6))

print("\nNew Random Row:\n", new_row)

# Add row to matrix
matrix = np.vstack((matrix, new_row))

print("\nMatrix after adding new row:\n", matrix)

# Sum of each row
row_sum = matrix.sum(axis=1)

print("\nSum of each row:\n", row_sum)


Original 5x6 Matrix:
 [[ 4 49 49  6 10 40]
 [36 24 18 27  9 49]
 [16  7  5  2 16 34]
 [30  8  2  2  9 22]
 [42 14 28  4 31 19]]

New Random Row:
 [[29  1 10 46 10 29]]

Matrix after adding new row:
 [[ 4 49 49  6 10 40]
 [36 24 18 27  9 49]
 [16  7  5  2 16 34]
 [30  8  2  2  9 22]
 [42 14 28  4 31 19]
 [29  1 10 46 10 29]]

Sum of each row:
 [158 163  80  73 138 125]


___
**Write a program to generate a ranodm integer matrix of size 5 X 6. Add another column containing random integers to it. Compute the sine of each element and print it**

In [5]:
# Generate random 5x6 integer matrix
matrix = np.random.randint(1, 50, size=(5, 6))

print("Original 5x6 Matrix:\n", matrix)

# Generate random column
new_column = np.random.randint(1, 50, size=(5, 1))

print("\nNew Random Column:\n", new_column)

# Add column to matrix
matrix = np.hstack((matrix, new_column))

print("\nMatrix after adding new column:\n", matrix)

# Compute sine of each element
sine_matrix = np.sin(matrix)

print("\nSine of each element:\n", sine_matrix)


Original 5x6 Matrix:
 [[45 37 32 38 35 12]
 [14 14 36 47 38 24]
 [41 34 46 44  7  2]
 [14 27 28 31 27 37]
 [13 35 10  7  5 31]]

New Random Column:
 [[41]
 [29]
 [37]
 [11]
 [44]]

Matrix after adding new column:
 [[45 37 32 38 35 12 41]
 [14 14 36 47 38 24 29]
 [41 34 46 44  7  2 37]
 [14 27 28 31 27 37 11]
 [13 35 10  7  5 31 44]]

Sine of each element:
 [[ 0.85090352 -0.64353813  0.55142668  0.29636858 -0.42818267 -0.53657292
  -0.15862267]
 [ 0.99060736  0.99060736 -0.99177885  0.12357312  0.29636858 -0.90557836
  -0.66363388]
 [-0.15862267  0.52908269  0.90178835  0.01770193  0.6569866   0.90929743
  -0.64353813]
 [ 0.99060736  0.95637593  0.27090579 -0.40403765  0.95637593 -0.64353813
  -0.99999021]
 [ 0.42016704 -0.42818267 -0.54402111  0.6569866  -0.95892427 -0.40403765
   0.01770193]]


___
**Write a program to generate a ranodm matrix of size 5 X 6. Consider the 3rd and 4th row; and 2nd, 3rd and 4th column and print the resultant matrix using slicing**

In [6]:
# Generate random 5x6 matrix
matrix = np.random.randint(1, 50, size=(5, 6))

print("Original Matrix:\n", matrix)

# Select 3rd & 4th rows and 2nd, 3rd & 4th columns
# (Indexing starts from 0)
result = matrix[2:4, 1:4]

print("\nResultant Matrix after slicing:\n", result)


Original Matrix:
 [[42  1 23  5 14 12]
 [30  5 22  5 10 17]
 [34 46  5 40 20 38]
 [15 47 36 43 36 31]
 [32 39 28 31 34 20]]

Resultant Matrix after slicing:
 [[46  5 40]
 [47 36 43]]
